Update data_structure_ic13.py
fixing the error 
ValueError: invalid literal for int() with base 10: '58 128 411 181 "Footpath"'
and making bbox in the shape format that is required.